export const department = [null,
    'Tourism',
    'Geography', 
    'History', 
    'Khmer Liturature', 
    'Philosophy',
    'Psychology',
    'Sociology',
    'Media and Communication',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Science',
    'Environmental Science',
    'Mathematics',
    'English',
    'French',
    'Japan',
    'Korea',
    'Social Work',
    'Chinese',
    'International Study',
    'International Business Management',
    'Economic Development',
    'Natural Resource Management & Development',
    'Community Development',
    'Telecommunication & Electronic Engineering',
    'Bioengineering',
    'ITE',
    'Thai',
    'Linguistic',
    'Lifelong Learning',
    'Educational Studies',
    'Higher Education Development and Management',
    'Automation and Supply Chain Systems Engineering',
    'Food Technology and Engineering',
    'Data Science and Engineering',
    'Environmental Engineering',
    'International Economics',
    'Political Science and Public Policy',
    'Sustainable Urban Planning and Development'
];